#!/usr/bin/env python3
"""Generate jr-ring kernels: N contiguous 24-byte handlers (auipc, addi, 3 nops, jr),
handler 0 also carrying the round counter. Optionally a jitter variant whose
handler 0 branches on a pseudo-random table entry (a1 = table pointer).
Usage: gen_rings.py <out.S> N1 N2 ...   (also emits k_ringjit16)"""
import sys

def ring(name, n, jitter=False):
    o = [f"    .globl k_{name}", "    .balign 64", f"k_{name}:", f"{name}_h0:",
         "    addi a0, a0, -1", f"    beqz a0, {name}_done"]
    if jitter:
        # load next table word, advance pointer, branch on its low bit (data dependent)
        o += ["    lw   t2, 0(a1)", "    addi a1, a1, 4", "    andi t2, t2, 1",
              f"    beqz t2, {name}_j0", "    addi a5, a5, 1", f"{name}_j0:"]
    for i in range(n):
        tgt = f"{name}_h{(i + 1) % n}"
        if i > 0:
            o.append(f"{name}_h{i}:")
        o += [f"5:  auipc t1, %pcrel_hi({tgt})", "    addi  t1, t1, %pcrel_lo(5b)",
              "    nop", "    nop", "    nop", "    jr    t1"]
    o += [f"{name}_done:", "    ret", ""]
    return "\n".join(o)

def main():
    out = sys.argv[1]
    ns = [int(x) for x in sys.argv[2:]]
    s = ["/* generated by scripts/gen_rings.py */", "    .text", "    .option norelax", ""]
    for n in ns:
        s.append(ring(f"ring{n}", n))
    s.append(ring("ringjit16", 16, jitter=True))
    open(out, "w").write("\n".join(s) + "\n")

if __name__ == "__main__":
    main()
